# Generated by Django 3.0.2 on 2020-01-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('school', models.CharField(db_index=True, max_length=100, unique=True)),
                ('major', models.CharField(db_index=True, max_length=100, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('job_title', models.CharField(db_index=True, max_length=100, unique=True)),
                ('company', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
